name: Build and Push Docker Image To AWS ECR Private
on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Make application-prod.properties
      run: |
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.PROPERTIES_RDS }}" > ./application.properties
      shell: bash
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Naming jar file
      run: mv ./target/*.jar ./target/app.jar

    - name: Check jar file
      run: ls ./target

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
   # - run: docker buildx build -t app .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR Private
      id: login-ecr-private
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Build, tag, and push docker image to Amazon ECR Private
      env:
        REGISTRY_ALIAS: ${{ secrets.ECR_PRIVATE_ID }}
        REPOSITORY: app-with-ecs
        IMAGE_TAG: latest
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_PRIVATE_ID }}
        docker build -t $REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
